version: '3.7'

services:
  app:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    # depends_on:
    #   - database
  database:
    image: mdillon/postgis
    ports:
      - 5432:5432